// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGFFRA46RWLyvbe_tnX9aetKVruuehJCA',
    appId: '1:997297148586:web:3b8ec7cb09a699f64c76d3',
    messagingSenderId: '997297148586',
    projectId: 'auonproject2',
    authDomain: 'auonproject2.firebaseapp.com',
    storageBucket: 'auonproject2.firebasestorage.app',
    measurementId: 'G-1W0G30FV6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNwGeKs_MGKcB0HLQGE2QVJcU8x2mcSeE',
    appId: '1:997297148586:android:20a0b4d0364bfa364c76d3',
    messagingSenderId: '997297148586',
    projectId: 'auonproject2',
    storageBucket: 'auonproject2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp08TIzrmfWSiTOND93N1nFsFgpzrcBO0',
    appId: '1:997297148586:ios:aaed4620af70a1894c76d3',
    messagingSenderId: '997297148586',
    projectId: 'auonproject2',
    storageBucket: 'auonproject2.firebasestorage.app',
    iosBundleId: 'com.example.aounproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp08TIzrmfWSiTOND93N1nFsFgpzrcBO0',
    appId: '1:997297148586:ios:aaed4620af70a1894c76d3',
    messagingSenderId: '997297148586',
    projectId: 'auonproject2',
    storageBucket: 'auonproject2.firebasestorage.app',
    iosBundleId: 'com.example.aounproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGFFRA46RWLyvbe_tnX9aetKVruuehJCA',
    appId: '1:997297148586:web:c9799974a131eda54c76d3',
    messagingSenderId: '997297148586',
    projectId: 'auonproject2',
    authDomain: 'auonproject2.firebaseapp.com',
    storageBucket: 'auonproject2.firebasestorage.app',
    measurementId: 'G-33CNV315E8',
  );

}